name: Build and Publish

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Upload to s3
        run: |
          aws s3 rm s3://widgets.wotstat.info --endpoint-url=https://storage.yandexcloud.net/ --recursive

          aws s3 cp \
            dist/ s3://widgets.wotstat.info \
            --endpoint-url=https://storage.yandexcloud.net/ \
            --cache-control 'public, max-age=86400' \
            --recursive

          aws s3 cp \
            s3://widgets.wotstat.info/assets/ s3://widgets.wotstat.info/assets/ \
            --endpoint-url=https://storage.yandexcloud.net/ \
            --recursive \
            --cache-control "public, max-age=31104000"

          aws s3 cp \
            s3://widgets.wotstat.info/index.html s3://widgets.wotstat.info/index.html \
            --endpoint-url=https://storage.yandexcloud.net/ \
            --cache-control "public, max-age=300"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ru-central1